name: SlimefunAddon
author: JasperChaseTOQ
description: A slimefun 4 addon by JasperChaseTOQ
main: me.jasperchasetoq.slimefunaddon.ExampleAddon
website: https://github.com/JasperChaseTOQ/
version: ${project.version}
api-version: 1.17
depend: [Slimefun]